version: '3.8'

services:

  jxo-test:
    image: joshuaxong/jxo-test
    working_dir: /jxo-test
    build: .
    ports:
      - 8080:8080
    environment:
      - CONNECTION_STRING=mongodb://mongo:27017/
    volumes:
      - ./:/jxo-test # I'm pretty sure this volume is of a different type from (1)
    command: npm start

  mongo:
    image: mongo:4.2.8
    ports:
      - 27017:27017
    volumes:
      - database-data:/data/db # (1)
      - database-data:/data/configdb # (1)

  postgres:
    image: postgres:13
    ports:
      - 5432:5432
    volumes:
      - database-data:/etc/postgresql/13/data # (1)

volumes:
  database-data:
